### ISSUE TITLE
THe code does not do anything 

### ISSUE THREAD

**Issue by gkowalski** [whytestalyon/lattice#1]
Hmm, the latticeloader.LatticeLoader class is the only one with a main() method and it does not do any work ... :-(

**Comment by whytestalyon** [comment]
Yeah, I see that, it's only the original code from the start of the project... I don't have my personal machine on me right now but I'll go take a look at it once I get back home on Sunday and update. I either pushed up the wrong branch or the updated code lives on Mel's old Mac at MCW and I'll have to remote in to check on there for it. Either way I'll find it.

**Comment by whytestalyon** [comment]
@gkowalski All fixed, you should be good to go now. I hadn't realized that I moved the project to use Maven instead of Ant for build and dependency management and moved the repo to a different directory without deleting the original. Please give this a go and let me know if you have any issues with it.
